# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-08 13:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180208_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='second_name',
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2018, 2, 8, 13, 28, 33, 742400, tzinfo=utc), verbose_name='Birth date of user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Department of User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name of User'),
        ),
    ]
