# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-12 07:59
from __future__ import unicode_literals

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0007_user_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=datetime.date(2018, 2, 12), verbose_name='Birth date of user'),
        ),
    ]
