# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 09:07
from __future__ import unicode_literals

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0011_auto_20180219_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student',
            field=models.BooleanField(default=True, verbose_name='Student or not'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2018, 2, 19, 9, 7, 15, 277264, tzinfo=utc),
                                   verbose_name='Birth date of user'),
        ),
    ]
