# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 09:10
from __future__ import unicode_literals

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0012_auto_20180219_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='student',
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2018, 2, 19, 9, 10, 22, 395448, tzinfo=utc),
                                   verbose_name='Birth date of user'),
        ),
    ]
