# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-23 10:18
from __future__ import unicode_literals

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0021_auto_20180219_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2018, 2, 23, 10, 18, 45, 324541, tzinfo=utc),
                                   verbose_name='Birth date of user'),
        ),
    ]
