# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-22 03:22
from __future__ import unicode_literals

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0027_auto_20180320_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.IntegerField()),
                ('education_related', models.IntegerField()),
                ('other', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2000, 4, 27, 3, 22, 47, 309990, tzinfo=utc),
                                   verbose_name='Birth date of user'),
        ),
        migrations.AddField(
            model_name='usage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                    verbose_name='user'),
        ),
    ]
