# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-22 05:20
from __future__ import unicode_literals

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0029_auto_20180422_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usage',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2000, 4, 27, 5, 20, 17, 336515, tzinfo=utc),
                                   verbose_name='Birth date of user'),
        ),
    ]
