# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-22 06:33
from __future__ import unicode_literals

import datetime

import django.db.models.deletion
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0031_auto_20180422_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(help_text='Group of the user', max_length=20, verbose_name='group_number')),
            ],
        ),
        migrations.RemoveField(
            model_name='usage',
            name='class_of_user',
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2000, 4, 27, 6, 33, 31, 726157, tzinfo=utc),
                                   verbose_name='Birth date of user'),
        ),
        migrations.AddField(
            model_name='usage',
            name='group',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='users.UserGroup',
                                    verbose_name='group of user'),
            preserve_default=False,
        ),
    ]
