# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-22 06:38
from __future__ import unicode_literals

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0032_auto_20180422_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergroup',
            old_name='group',
            new_name='group_number',
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2000, 4, 27, 6, 38, 14, 736259, tzinfo=utc),
                                   verbose_name='Birth date of user'),
        ),
    ]
