# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-22 06:41
from __future__ import unicode_literals

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0033_auto_20180422_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='group_number',
        ),
        migrations.AddField(
            model_name='usergroup',
            name='group',
            field=models.IntegerField(default=1, help_text='Group of the user', verbose_name='group number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2000, 4, 27, 6, 40, 59, 552686, tzinfo=utc),
                                   verbose_name='Birth date of user'),
        ),
    ]
