# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-22 06:43
from __future__ import unicode_literals

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0034_auto_20180422_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2000, 4, 27, 6, 43, 1, 504282, tzinfo=utc),
                                   verbose_name='Birth date of user'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='group',
            field=models.IntegerField(help_text='Group of the user', unique=True, verbose_name='group number'),
        ),
    ]
