# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-22 07:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_auto_20180422_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usage',
            name='education',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usage',
            name='education_related',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usage',
            name='other',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2000, 4, 27, 7, 46, 35, 310401, tzinfo=utc), verbose_name='Birth date of user'),
        ),
    ]
